"""
Step 7: 打包 seed.md — 把最终角色表渲染成 MiroFish 可用的种子文档。

输入: artifacts/characters_final.json  (step6 输出)
输出: artifacts/seed.md
"""
from __future__ import annotations

import json
from pathlib import Path

from pipeline import config


SEED_TEMPLATE = """# PEP Mirofish — Character Seed

> Auto-generated by PEP Mirofish pipeline.
> Do not edit manually — re-run step6 to make changes.

## Characters

{characters}

---

## How to Use

Upload this file as a seed in the MiroFish web UI.
MiroFish will use these personas to drive multi-agent character dialogues
on topics you provide.

## Character Index

{index}
"""


def load_final() -> list[dict]:
    path = config.CHARACTERS_FINAL
    if not path.exists():
        raise SystemExit(f"not found: {path}, run step6 and save first")
    return json.loads(path.read_text(encoding="utf-8"))


def render_character(c: dict) -> str:
    name = c.get("name", "Unknown")
    traits = c.get("personality_traits", [])
    interests = c.get("interests", [])
    relationships = c.get("relationships", [])
    dialogues = c.get("dialogues", [])

    lines = [f"### {name}"]
    lines.append("")

    if traits:
        lines.append(f"**性格**: {', '.join(traits)}")
    if interests:
        lines.append(f"**爱好**: {', '.join(interests)}")
    if relationships:
        lines.append(f"**关系**: {', '.join(relationships)}")
    if dialogues:
        lines.append("")
        lines.append("**台词示例**:")
        for d in dialogues:
            lines.append(f"> {d}")

    return "\n".join(lines)


def main() -> None:
    chars = load_final()
    print(f"[step7] {len(chars)} characters to pack")

    char_sections = [render_character(c) for c in chars]
    characters_md = "\n\n---\n\n".join(char_sections)

    index_lines = [f"- **{c['name']}**" for c in chars]
    index_md = "\n".join(index_lines)

    seed = SEED_TEMPLATE.format(
        characters=characters_md,
        index=index_md,
    )

    out = config.SEED_MD
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(seed, encoding="utf-8")

    print(f"[step7] → {out}  ({len(seed)} chars)")


if __name__ == "__main__":
    main()
